
service: my-api-serverless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: 
        - arn:aws:dynamodb:us-east-1:171267240569:table/MarcaTable



functions:
  servicioGETALL:
    handler: src/handlers/handlerGETSWAPI.servicioALLGETSWAPI
    events: 
      - httpApi:
          path: /api/serviciogetswpi
          method: get
  
  serviceGET:
     handler: src/handlers/handlerGETSWAPI.servicioGETSWAPI
     events:
       - httpApi:
          path: /api/serviciogetswpi/{codigo}
          method: get
  

  servicePostMarca:
     handler: src/handlers/handlerMarca.servicePostMarca
     events:
       - httpApi:
          path: /api/marcas
          method: post
  serviceGetAllMarca:
     handler: src/handlers/handlerMarca.serviceGetAllMarcas
     events:
       - httpApi:
          path: /api/marcas
          method: get



resources:
  Resources:
    usuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MarcaTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH